user:
  outputs:
    default:
      account: WAFUAAY-PC58939
      auth_type: password
      client_session_keep_alive: true
      connect_retries: 3
      connect_timeout: 30
      database: AIRBNB
      password: Endrajit@150989
      retry_on_database_errors: true
      role: null
      schema: dbt_jsahay
      threads: 6
      type: snowflake
      user: jitendrasahay89
      warehouse: COMPUTE_WH
  target: default
